services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ecoride_php
    volumes:
      - ./:/var/www/html:cached
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://ecorideuser:ecoridepassword@mysql:3306/ecoride?charset=utf8mb4"
    depends_on:
      - mysql
    networks: [stack]

  nginx:
    image: nginx:stable
    container_name: ecoride_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks: [stack]

  mysql:
    image: mysql:8.2
    container_name: ecoride_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"   # si tu veux accéder à MySQL depuis Windows: localhost:3307
    volumes:
      - db_data:/var/lib/mysql
    networks: [stack]

networks:
  stack:

volumes:
  db_data:
